import { Report } from "../schemas/report.schema";

export const ReportsMock: Report[] = [
    {
        type: 'project',
        content: 'This project is not good because it is not good.',
        projectId: null,
        reportedUser: null,
        userId: null,
        visited: false,
        action: false,
        isMockData: true,
    },
    {
        type: 'comment',
        content: 'This comment is not good, as it is not good.',
        projectId: null,
        reportedUser: null,
        userId: null,
        visited: false,
        action: false,
        isMockData: true,
    },
    {
        type: 'user',
        content: 'This user is not good because he is not good.',
        projectId: null,
        reportedUser: null,
        userId: null,
        visited: false,
        action: false,
        isMockData: true,
    },
    {
        type: 'project',
        content: 'I woud like to report this project, because it is not good.',
        projectId: null,
        reportedUser: null,
        userId: null,
        visited: false,
        action: false,
        isMockData: true,
    },
    {
        type: 'comment',
        content: 'I woud like to report this comment, because it is not good.',
        projectId: null,
        reportedUser: null,
        userId: null,
        visited: false,
        action: false,
        isMockData: true,
    },
    {
        type: 'user',
        content: 'I woud like to report this user, because he is not good.',
        projectId: null,
        reportedUser: null,
        userId: null,
        visited: false,
        action: false,
        isMockData: true,
    }
];