version: '3.8'

services:
  # Backend Service
  backend-dev:
    container_name: backend-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./uploads:/app/uploads
    ports:
      - "6000:6000"
    depends_on:
      - db-mongo-dev
    networks:
      - server-network-dev

  # MongoDB Service
  db-mongo-dev:
    container_name: db-mongo-dev
    image: mongo
    volumes:
      - mongo-data:/data/db-dev
    restart: unless-stopped
    networks:
      - server-network-dev

volumes:
  mongo-data:

networks:
  server-network-dev:
    driver: bridge