version: '3.8'

services:
  admin-panel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-admin
    ports:
      - "4200:80"
    restart: unless-stopped
    networks:
      - admin-network
    environment:
      - API_URL=https://api.campusconnects.de

networks:
  admin-network:
    driver: bridge