version: '3.8'

services:
  backend-ai:
    container_name: backend-ai
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ai-testing.env
    volumes:
      - ./uploads:/app/uploads
    ports:
      - "7000:7000"
    depends_on:
      - db-mongo-ai
    networks:
      - server-network-ai

  db-mongo-ai:
    container_name: db-mongo-ai
    image: mongo
    volumes:
      - mongo-data-ai:/data/db
    restart: unless-stopped
    networks:
      - server-network-ai
      
volumes:
  mongo-data-ai:

networks:
  server-network-ai:
    driver: bridge
