import { Project } from "../schemas/project.schema"

export const ProjectsMock: Project[] = [
    {
        title: 'The impact of AI on the future of education',
        description: 'Artificial Intelligence (AI) is poised to revolutionize the educational landscape by providing personalized learning experiences, enhancing curriculum development, and automating administrative tasks. As AI technologies evolve, they offer unprecedented opportunities to tailor education to individual needs, improve accessibility, and foster innovation in teaching and learning methodologies, ultimately shaping the future of education.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'Exploring Renewable Energy Solutions',
        description: 'Renewable energy sources such as solar, wind, and hydro are critical in mitigating climate change. This project explores innovative technologies and strategies to harness these resources more efficiently, reduce costs, and increase adoption globally.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'The Role of Blockchain in Supply Chain Management',
        description: 'Blockchain technology offers a secure and transparent method for managing supply chains. This project examines its potential to improve traceability, reduce fraud, and enhance efficiency in global trade and logistics.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'Developing Sustainable Urban Planning Models',
        description: 'This research focuses on sustainable urban development strategies, including green architecture, efficient public transport systems, and renewable energy integration, to create smart and livable cities for the future.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'Innovations in Healthcare Technology',
        description: 'The integration of AI and IoT in healthcare is transforming patient care. This project explores advancements in medical diagnostics, telemedicine, and wearable health monitoring devices.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'Cybersecurity Challenges in the Digital Age',
        description: 'As the digital world expands, cybersecurity threats grow in complexity. This project investigates emerging threats and innovative solutions to protect sensitive data and infrastructure.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'The Evolution of E-Commerce Platforms',
        description: 'E-commerce has revolutionized shopping experiences worldwide. This project examines the latest trends in platform development, customer experience enhancement, and logistics optimization.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'Enhancing Agricultural Productivity with IoT',
        description: 'IoT applications in agriculture are optimizing water use, monitoring soil health, and improving crop yields. This project explores cutting-edge IoT solutions for smarter farming practices.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'Advancements in Electric Vehicle Technology',
        description: 'Electric vehicles are at the forefront of sustainable transportation. This project investigates battery innovations, charging infrastructure, and market adoption trends.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'The Impact of Virtual Reality on Mental Health Treatment',
        description: 'Virtual reality is emerging as a powerful tool for mental health therapy, offering immersive experiences for treating PTSD, anxiety, and phobias. This project examines its effectiveness and potential applications.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'Exploring Quantum Computing for Cryptography',
        description: 'Quantum computing promises to revolutionize cryptographic methods. This project explores its potential to enhance security protocols and protect sensitive information from cyber threats.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'The Role of Big Data in Modern Business Analytics',
        description: 'Big data analytics is transforming business decision-making processes. This project investigates tools and techniques for leveraging large datasets to gain actionable insights.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'Innovative Solutions for Plastic Waste Management',
        description: 'The global plastic waste crisis demands innovative solutions. This project explores advanced recycling technologies, biodegradable alternatives, and waste reduction strategies.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'The Role of 5G in Enabling Smart Cities',
        description: '5G technology is the backbone of smart city development. This project explores its role in enhancing connectivity, enabling IoT applications, and improving urban living standards.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'The Future of Work: Remote and Hybrid Models',
        description: 'The COVID-19 pandemic accelerated the adoption of remote and hybrid work models. This project examines their long-term impact on productivity, employee well-being, and organizational culture.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'AI-Driven Innovations in Financial Technology',
        description: 'Artificial intelligence is reshaping the fintech industry by automating processes, enhancing fraud detection, and personalizing financial services. This project explores its transformative impact.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'The Ethics of Artificial Intelligence Development',
        description: 'As AI systems grow in influence, ethical considerations become crucial. This project investigates issues of bias, accountability, and transparency in AI development and deployment.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'The Rise of Esports and Its Cultural Impact',
        description: 'Esports has become a global phenomenon, blending gaming with competitive sports. This project explores its growth, audience engagement, and potential as a mainstream entertainment industry.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'The Role of AI in Disaster Response',
        description: 'AI is playing a pivotal role in disaster management by enhancing early warning systems, optimizing resource allocation, and improving recovery efforts. This project examines its applications and effectiveness.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'The Potential of Gene Editing in Healthcare',
        description: 'Gene editing technologies like CRISPR offer revolutionary possibilities in treating genetic disorders, enhancing disease resistance, and improving agricultural productivity. This project explores ethical and practical implications.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'Exploring Space Tourism Opportunities',
        description: 'The commercialization of space travel is bringing space tourism closer to reality. This project investigates the challenges and opportunities in making space accessible to civilians.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'The Future of Autonomous Vehicles',
        description: 'Autonomous vehicles are revolutionizing the transportation industry by enhancing safety, reducing traffic congestion, and optimizing energy efficiency. This project explores the latest advancements, challenges, and ethical implications of self-driving technology.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'Enhancing Education Through Gamification',
        description: 'Gamification in education leverages game design elements to motivate and engage learners. This project explores the use of gamified tools and strategies to enhance learning outcomes and foster a love for learning.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'The Role of Social Media in Modern Marketing',
        description: 'Social media has transformed how businesses interact with customers. This project examines strategies for leveraging social platforms to build brand awareness, drive engagement, and achieve marketing goals.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'The Impact of Climate Change on Global Agriculture',
        description: 'Climate change poses significant challenges to global food security. This project investigates its impact on agricultural productivity, exploring adaptive strategies to ensure sustainable food production.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'Advancing Robotics for Healthcare Applications',
        description: 'Robotics is transforming healthcare by improving surgical precision, automating repetitive tasks, and enhancing patient care. This project explores the latest robotic technologies and their applications in the medical field.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'The Growth of Sustainable Fashion',
        description: 'Sustainable fashion emphasizes environmentally friendly practices in the apparel industry. This project explores innovations in sustainable materials, ethical production methods, and consumer awareness campaigns.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'Leveraging AI for Personalized Healthcare',
        description: 'AI-driven healthcare solutions offer personalized treatment plans based on patient data and predictive analytics. This project investigates the potential of AI in revolutionizing patient care and improving health outcomes.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'The Rise of Digital Nomadism',
        description: 'Digital nomadism is reshaping the modern workforce, offering flexibility and a new way of living. This project explores the benefits, challenges, and tools enabling remote work from anywhere in the world.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'The Role of AI in Predictive Maintenance',
        description: 'AI-powered predictive maintenance reduces equipment downtime and extends the life of machinery. This project explores its applications in various industries, including manufacturing and transportation.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    },
    {
        title: 'Exploring the Future of Renewable Energy Storage',
        description: 'Efficient energy storage systems are critical to maximizing the potential of renewable energy. This project investigates advancements in battery technology, grid storage solutions, and their role in a sustainable energy future.',
        attachments: [],
        courses: [],
        isDraft: false,
        links: [],
        owner: null,
        tags: [],
        teamMembers: [],
        thumbnail: null, isMockData: true,
    }
];