import { Tag } from "../schemas/tag.schema"

export const tagsMock: Tag[] = [
    { name: 'Artificial Intelligence', type: 'tag', user: null, isMockData: true, },
    { name: 'Machine Learning', type: 'tag', user: null, isMockData: true, },
    { name: 'Deep Learning', type: 'tag', user: null, isMockData: true, },
    { name: 'Computer Vision', type: 'tag', user: null, isMockData: true, },
    { name: 'Robotics', type: 'tag', user: null, isMockData: true, },
    { name: 'Data Science', type: 'tag', user: null, isMockData: true, },
    { name: 'Data Engineering', type: 'tag', user: null, isMockData: true, },
    { name: 'Data Analytics', type: 'tag', user: null, isMockData: true, },
    { name: 'Data Visualization', type: 'tag', user: null, isMockData: true, },
    { name: 'Data Management', type: 'tag', user: null, isMockData: true, },
    { name: 'Data Mining', type: 'tag', user: null, isMockData: true, },
    { name: 'Computer Engineering', type: 'studyProgram', user: null, isMockData: true, },
    { name: 'Information Technology', type: 'studyProgram', user: null, isMockData: true, },
    { name: 'Computer Science', type: 'studyProgram', user: null, isMockData: true, },
    { name: 'Electrical Engineering', type: 'studyProgram', user: null, isMockData: true, },
    { name: 'Mechanical Engineering', type: 'studyProgram', user: null, isMockData: true, },
    { name: 'Civil Engineering', type: 'studyProgram', user: null, isMockData: true, },
    { name: 'Biomedical Engineering', type: 'studyProgram', user: null, isMockData: true, },
    { name: 'Chemical Engineering', type: 'studyProgram', user: null, isMockData: true, },
    { name: 'Aerospace Engineering', type: 'studyProgram', user: null, isMockData: true, },
    { name: 'Nanotechnology', type: 'studyProgram', user: null, isMockData: true, },
    { name: 'AI and Machine Learning', type: 'course', user: null, isMockData: true, },
    { name: 'Deep Learning', type: 'course', user: null, isMockData: true, },
    { name: 'Computer Vision', type: 'course', user: null, isMockData: true, },
    { name: 'Robotics', type: 'course', user: null, isMockData: true, },
    { name: 'Data Science', type: 'course', user: null, isMockData: true, },
    { name: 'Data Engineering', type: 'course', user: null, isMockData: true, },
    { name: 'Data Analytics', type: 'course', user: null, isMockData: true, },
    { name: 'Data Visualization', type: 'course', user: null, isMockData: true, },
    { name: 'Data Management', type: 'course', user: null, isMockData: true, },
    { name: 'Data Mining', type: 'course', user: null, isMockData: true, },
    { name: 'Artificial Intelligence', type: 'course', user: null, isMockData: true, },
    { name: 'Machine Learning', type: 'course', user: null, isMockData: true, }
]