import { User } from "../schemas/user.schema";

export const usersMock: User[] = [
    {
        firstName: 'John',
        lastName: 'Doe',
        email: 'john.doe@example.com',
        username: 'john_doe',
        password: 'Pass@123456',
        userType: 'student',
        profilePicture: null,
        interestedTags: [],
        interestedCourses: [],
        studyPrograms: [],
        softDeleted: false,
        isBlockedByAdmin: false,
        status: true,
        code: null,
        codeExpire: null, isMockData: true,
    },
    {
        firstName: 'Jane',
        lastName: 'Smith',
        email: 'jane.smith@example.com',
        username: 'jane_smith',
        password: 'Pass@123456',
        userType: 'lecturer',
        profilePicture: null,
        interestedTags: [],
        interestedCourses: [],
        studyPrograms: [],
        softDeleted: false,
        isBlockedByAdmin: false,
        status: true,
        code: null,
        codeExpire: null, isMockData: true,
    },
    {
        firstName: 'Alice',
        lastName: 'Johnson',
        email: 'alice.johnson@example.com',
        username: 'alice.j',
        password: 'Pass@123456',
        userType: 'student',
        profilePicture: null,
        interestedTags: [],
        interestedCourses: [],
        studyPrograms: [],
        softDeleted: false,
        isBlockedByAdmin: false,
        status: true,
        code: null,
        codeExpire: null, isMockData: true,
    },
    {
        firstName: 'Robert',
        lastName: 'Williams',
        email: 'robert.williams@example.com',
        username: 'robert.w',
        password: 'Pass@123456',
        userType: 'lecturer',
        profilePicture: null,
        interestedTags: [],
        interestedCourses: [],
        studyPrograms: [],
        softDeleted: false,
        isBlockedByAdmin: false,
        status: true,
        code: null,
        codeExpire: null, isMockData: true,
    },
    {
        firstName: 'Emily',
        lastName: 'Davis',
        email: 'emily.davis@example.com',
        username: 'emily.d',
        password: 'Pass@123456',
        userType: 'student',
        profilePicture: null,
        interestedTags: [],
        interestedCourses: [],
        studyPrograms: [],
        softDeleted: false,
        isBlockedByAdmin: false,
        status: true,
        code: null,
        codeExpire: null, isMockData: true,
    },
    {
        firstName: 'Michael',
        lastName: 'Brown',
        email: 'michael.brown@example.com',
        username: 'michael_b',
        password: 'Pass@123456',
        userType: 'lecturer',
        profilePicture: null,
        interestedTags: [],
        interestedCourses: [],
        studyPrograms: [],
        softDeleted: false,
        isBlockedByAdmin: false,
        status: true,
        code: null,
        codeExpire: null, isMockData: true,
    },
    {
        firstName: 'Sarah',
        lastName: 'Miller',
        email: 'sarah.miller@example.com',
        username: 'sarah.m',
        password: 'Pass@123456',
        userType: 'student',
        profilePicture: null,
        interestedTags: [],
        interestedCourses: [],
        studyPrograms: [],
        softDeleted: false,
        isBlockedByAdmin: false,
        status: true,
        code: null,
        codeExpire: null, isMockData: true,
    },
    {
        firstName: 'William',
        lastName: 'Taylor',
        email: 'william.taylor@example.com',
        username: 'will_taylor',
        password: 'Pass@123456',
        userType: 'lecturer',
        profilePicture: null,
        interestedTags: [],
        interestedCourses: [],
        studyPrograms: [],
        softDeleted: false,
        isBlockedByAdmin: false,
        status: true,
        code: null,
        codeExpire: null, isMockData: true,
    },
    {
        firstName: 'Sophia',
        lastName: 'Anderson',
        email: 'sophia.anderson@example.com',
        username: 'sophia.a',
        password: 'Pass@123456',
        userType: 'student',
        profilePicture: null,
        interestedTags: [],
        interestedCourses: [],
        studyPrograms: [],
        softDeleted: false,
        isBlockedByAdmin: false,
        status: true,
        code: null,
        codeExpire: null, isMockData: true,
    },
    {
        firstName: 'James',
        lastName: 'Lee',
        email: 'james.lee@example.com',
        username: 'james.lee',
        password: 'Pass@123456',
        userType: 'lecturer',
        profilePicture: null,
        interestedTags: [],
        interestedCourses: [],
        studyPrograms: [],
        softDeleted: false,
        isBlockedByAdmin: false,
        status: true,
        code: null,
        codeExpire: null, isMockData: true,
    },
    {
        firstName: 'Olivia',
        lastName: 'Moore',
        email: 'olivia.moore@example.com',
        username: 'olivia.m',
        password: 'Pass@123456',
        userType: 'student',
        profilePicture: null,
        interestedTags: [],
        interestedCourses: [],
        studyPrograms: [],
        softDeleted: false,
        isBlockedByAdmin: false,
        status: true,
        code: null,
        codeExpire: null, isMockData: true,
    },
    {
        firstName: 'Daniel',
        lastName: 'White',
        email: 'daniel.white@example.com',
        username: 'daniel.w',
        password: 'Pass@123456',
        userType: 'lecturer',
        profilePicture: null,
        interestedTags: [],
        interestedCourses: [],
        studyPrograms: [],
        softDeleted: false,
        isBlockedByAdmin: false,
        status: true,
        code: null,
        codeExpire: null, isMockData: true,
    },
    {
        firstName: 'Charlotte',
        lastName: 'Harris',
        email: 'charlotte.harris@example.com',
        username: 'charlotte_h',
        password: 'Pass@123456',
        userType: 'student',
        profilePicture: null,
        interestedTags: [],
        interestedCourses: [],
        studyPrograms: [],
        softDeleted: false,
        isBlockedByAdmin: false,
        status: true,
        code: null,
        codeExpire: null, isMockData: true,
    },
    {
        firstName: 'Matthew',
        lastName: 'Martin',
        email: 'matthew.martin@example.com',
        username: 'matthew_m',
        password: 'Pass@123456',
        userType: 'lecturer',
        profilePicture: null,
        interestedTags: [],
        interestedCourses: [],
        studyPrograms: [],
        softDeleted: false,
        isBlockedByAdmin: false,
        status: true,
        code: null,
        codeExpire: null, isMockData: true,
    },
    {
        firstName: 'Amelia',
        lastName: 'Thompson',
        email: 'amelia.thompson@example.com',
        username: 'amelia.t',
        password: 'Pass@123456',
        userType: 'student',
        profilePicture: null,
        interestedTags: [],
        interestedCourses: [],
        studyPrograms: [],
        softDeleted: false,
        isBlockedByAdmin: false,
        status: true,
        code: null,
        codeExpire: null, isMockData: true,
    },
    {
        firstName: 'Henry',
        lastName: 'Garcia',
        email: 'henry.garcia@example.com',
        username: 'henry.g',
        password: 'Pass@123456',
        userType: 'lecturer',
        profilePicture: null,
        interestedTags: [],
        interestedCourses: [],
        studyPrograms: [],
        softDeleted: false,
        isBlockedByAdmin: false,
        status: true,
        code: null,
        codeExpire: null, isMockData: true,
    },
    {
        firstName: 'Isabella',
        lastName: 'Martinez',
        email: 'isabella.martinez@example.com',
        username: 'isabella.m',
        password: 'Pass@123456',
        userType: 'student',
        profilePicture: null,
        interestedTags: [],
        interestedCourses: [],
        studyPrograms: [],
        softDeleted: false,
        isBlockedByAdmin: false,
        status: true,
        code: null,
        codeExpire: null, isMockData: true,
    },
    {
        firstName: 'Alexander',
        lastName: 'Robinson',
        email: 'alex.robinson@example.com',
        username: 'alex.robinson',
        password: 'Pass@123456',
        userType: 'lecturer',
        profilePicture: null,
        interestedTags: [],
        interestedCourses: [],
        studyPrograms: [],
        softDeleted: false,
        isBlockedByAdmin: false,
        status: true,
        code: null,
        codeExpire: null, isMockData: true,
    },
    {
        firstName: 'Mia',
        lastName: 'Clark',
        email: 'mia.clark@example.com',
        username: 'mia.c',
        password: 'Pass@123456',
        userType: 'student',
        profilePicture: null,
        interestedTags: [],
        interestedCourses: [],
        studyPrograms: [],
        softDeleted: false,
        isBlockedByAdmin: false,
        status: true,
        code: null,
        codeExpire: null, isMockData: true,
    },
    {
        firstName: 'Liam',
        lastName: 'Lewis',
        email: 'liam.lewis@example.com',
        username: 'liam.lewis',
        password: 'Pass@123456',
        userType: 'lecturer',
        profilePicture: null,
        interestedTags: [],
        interestedCourses: [],
        studyPrograms: [],
        softDeleted: false,
        isBlockedByAdmin: false,
        status: true,
        code: null,
        codeExpire: null, isMockData: true,
    }
];